# Generated by Django 5.2.6 on 2026-08-06 17:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GeocodeCache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('query', models.CharField(db_index=True, max_length=255, unique=True)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('display_name', models.CharField(blank=True, max_length=512)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='FuelStation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opis_id', models.PositiveIntegerField(db_index=True, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=128)),
                ('state', models.CharField(max_length=8)),
                ('rack_id', models.PositiveIntegerField()),
                ('current_price', models.DecimalField(decimal_places=3, max_digits=6)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('geocode_source', models.CharField(choices=[('city', 'City centroid'), ('state_centroid', 'State/province centroid fallback')], max_length=32)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['opis_id'],
                'indexes': [models.Index(fields=['state', 'city'], name='routing_fue_state_217c0f_idx')],
            },
        ),
        migrations.CreateModel(
            name='PriceHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=3, max_digits=6)),
                ('effective_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='price_history', to='routing.fuelstation')),
            ],
            options={
                'verbose_name_plural': 'price histories',
                'ordering': ['station', 'effective_at'],
                'indexes': [models.Index(fields=['station', 'effective_at'], name='routing_pri_station_e57cf8_idx')],
            },
        ),
    ]
